image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay
    SPRING_PROFILE_ACTIVE: gitlab-ci
    USER_GITLAB: finderbar
    REPO: oauthapi
    CI_BUILD_TOKEN: q2wEUYyqy4gzwQrzDW-d
    CI_REGISTRY: registry.gitlab.com
    CI_REGISTRY_URI: $CI_REGISTRY/$USER_GITLAB/$REPO

stages:
    - build
    - package
    - deploy

maven-build:
    image: maven:3-jdk-8
    stage: build
    script: "mvn package -B"
    artifacts:
        paths:
            - target/*.war

package-build:
    stage: package
    script:
        - docker login -u theinlwin -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_URI .
        - docker push $CI_REGISTRY_URI

deploy-build:
    stage: deploy
    before_script:
        - docker login -u theinlwin -p $CI_BUILD_TOKEN $CI_REGISTRY
    script:
        - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
        - echo "$SERVER_SSH" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 700 ~/.ssh
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f ./dockerenv ]] && echo -e "Host *\n\tStrickHostKeyChecking no\n\n" > ~/.ssh/config'
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
        - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u theinlwin -p $CI_BUILD_TOKEN $CI_REGISTRY"
        - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $CI_REGISTRY_URI"
        - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP  "docker container stop $REPO && docker container rm $REPO || true"
        - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP  "docker run --name $REPO -p 8080:8080 -d $CI_REGISTRY_URI"

    environment:
        name: development
        url: http://192.241.142.173
